# Generated by Django 3.2.3 on 2021-05-18 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('foodName', models.CharField(max_length=100)),
                ('foodManufactureDate', models.DateTimeField(blank=True, null=True)),
                ('foodExpirationDate', models.DateTimeField(blank=True, null=True)),
                ('foodPrice', models.IntegerField(default=0)),
                ('foodAvailableDay', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tursday', 'Tursday'), ('Wenesday', 'Wenesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('voteId', models.AutoField(primary_key=True, serialize=False)),
                ('upVote', models.IntegerField(default=0)),
                ('downVote', models.IntegerField(default=0)),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_related', to='dashboard.food')),
            ],
        ),
    ]
