# Generated by Django 3.2.3 on 2021-05-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='foodExpirationDate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='foodManufactureDate',
        ),
        migrations.AddField(
            model_name='food',
            name='foodAddDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
