# Generated by Django 3.2.3 on 2021-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210518_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodAddDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
