# Generated by Django 3.2.3 on 2021-05-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210519_0228'),
        ('dashboard', '0003_alter_food_foodadddate'),
    ]

    operations = [
    ]
