# Generated by Django 3.2.3 on 2021-05-18 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20210519_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='foodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.food'),
        ),
    ]
